### ISSUE TITLE
found 3 (maybe 4) bugs with the theme

### ISSUE THREAD

**Issue by Overimagine1** [KillYoy/DiscordNight#18]
This theme is great (probably one of my favorites) but it does have its fair share of bugs with it that I wanna point out to make it better

![image](https://user-images.githubusercontent.com/79660414/117897216-4d7cee80-b290-11eb-85cf-ad94db70efbf.png)
I can't add channels

https://cdn.discordapp.com/attachments/460094358289514516/841821633572241429/image0.jpg
I can't take away roles (had to take this on my phone since Windows screenshots doesn't capture my cursor, sorry if its shit)

![image](https://user-images.githubusercontent.com/79660414/117897390-b06e8580-b290-11eb-9515-a299741cd01c.png)
the attachment button is unnecessarily small

![image](https://user-images.githubusercontent.com/79660414/117897658-37bbf900-b291-11eb-8ad3-e47d49935fc4.png)
When one user has no connections, it just looks so empty and weird

Thank you for the theme, and please do take your time fixing these issues :)

**Comment by KillYoy** [comment]
It's not bugs but intended changes to make everything fit better in a smaller window and to "declutter" Discord of things that can already be done through other means.
Creating, editing and sending invites to channels and removing/adding roles can already be done by right clicking and using the context menus.

The channel list icons can however be made visible again using the custom variables I have made in the theme.
Just add this code to the DiscordNight.theme.css or Custom CSS menu in Discord settings:
```css
:root {
	--Channel-Invite-Edit-Button: flex;			/* flex = ON, none = OFF */
	--Channel-Category-Invite-Button: flex;		/* flex = ON, none = OFF */
}
```

I am going to make the remove role button visible on hover in the future.

As for the profile it's like that because you have not added any connections, If you would fill out your profile with all connections it would all fit in nicely and you wouldn't have to scroll down to see them all like normally in Discord. It also makes seeing mutual servers/friends easier.

You can revert it back to Discords default by adding this code to the Custom CSS menu if you feel like.
```css
.modal-3c3bKg .root-SR8cQa .body-3ND3kc {
	min-height: 240px;
	height: 240px;
}
```

In my opinion the attachment button is completely unnecessary, you can just drag and drop things into the Discord window to upload stuff. The only reason it's even there is for people that still use it and in case Discord makes something that is only able to be done through it. Making it larger would either mean, moving it back to where it is originally or move the emoji button more to the left. Might look into improving this somehow in the future...
