### ISSUE TITLE
Friends list breaks when at ≥64 entries

### ISSUE THREAD

**Issue by GanerCodes** [KillYoy/DiscordNight#20]
![image](https://user-images.githubusercontent.com/34655998/119043949-38364d00-b97f-11eb-80ec-36cc07bde30a.png)

how fix?

**Comment by KillYoy** [comment]
This issue was caused by Discord adding lazy loading the friends list when you have ≥64 total entries in the list, this includes friends, pending invites and blocked users.
In the latest update I have now made it so when you reach this number the friends list it turns back into a list instead of a grid which fixes this issue.

**Comment by GanerCodes** [comment]
![image](https://user-images.githubusercontent.com/34655998/120087823-fd37c600-c0b0-11eb-8354-5682fbcd7fbd.png)
