### ISSUE TITLE
Scroll slider appearing on channels section when hovering over it

### ISSUE THREAD

**Issue by WitheredRose7** [KillYoy/DiscordNight#41]
Is there any way to make the scroll slider on channels section be visible permanently and not only when you hover over them? It moves everything little to the left when the slider appears.
Or at least somehow make space for it to appear, so it doesn't squish everything to the left.

**Comment by KillYoy** [comment]
Not always visible since that's something Discord does not even do normally until hovering over the section in servers that have a too long channel list.
There is definitely room for improvement how everything responds to the scrollbar appearing in the theme so it does not "squish" like you said. I will look into it.

**Comment by KillYoy** [comment]
Hovering over the sidebar should now not move the elements around but rather cut them slightly shorter making space for the scroller. Ought to be a better alternative to the elements being squished.
