### ISSUE TITLE
Discord Update (Profile & Settings Icons Bug)

### ISSUE THREAD

**Issue by thiaguinho4** [KillYoy/DiscordNight#44]
- The settings icons only appear when you click

![1](https://user-images.githubusercontent.com/101910294/191385241-268170c4-1c32-457a-8ac8-ba514e4c84b0.png)

- Profile pictures became smaller and the social network links became unable to be accessed because they can't be scrolled down

![2](https://user-images.githubusercontent.com/101910294/191386550-7a64913c-84a8-4e95-9bb2-4936a652c5ba.png)

Please fix these bugs, I love your theme and that's why I am creating issues for you to improve it even more

**Comment by SupertoineFR** [comment]
There seems to be a new issue related to clicking on your profile to set settings, as some of the formatting is entirely broken, such as:
Status, custom status and switch account not expanding to the full length (might be one of my plugins)
The custom "look" of the theme not even bothering to apply
and probably more that i'm not going to describe..
![image](https://user-images.githubusercontent.com/89167464/192086308-29336d84-f31c-4825-9e94-0a066219ad94.png)

**Comment by KillYoy** [comment]
Discord has been making constant adjustment to the profiles multiple times the past week. And with every change they re roll the classes so any change I make brakes immediately. Every user also does not share the same code currently since they are doing A/B testing with these changes. Once they calmed down with the changes I will update the theme and fix theses issues.

As for the settings icons their unique ID were removed so there is no option to tell them apart until you select one. 
I will just use the old method but that comes with its own drawbacks. If you would be missing one settings menu/they add a new one or it swapped place the icons would be out of order and appear on the wrong menu.
