### ISSUE TITLE
theres a bug on the avatar icons

### ISSUE THREAD

**Issue by Daku510** [KillYoy/DiscordNight#46]
bug for the avatar icons where its off centered 
https://user-images.githubusercontent.com/77857276/198796266-d7b2e6d9-1f01-48bd-a082-bf0148384d1d.png
example ^^^
https://user-images.githubusercontent.com/77857276/198796816-24776edf-f83c-4236-ae53-79889e51ee49.png
another example ^^^^

**Comment by TheLovinator1** [comment]
There is already an issue for that: #44

KillYoy said:
`Discord has been making constant adjustment to the profiles multiple times the past week. And with every change they re roll the classes so any change I make brakes immediately. Every user also does not share the same code currently since they are doing A/B testing with these changes. Once they calmed down with the changes I will update the theme and fix theses issues.`

So I guess we have to wait :eyes:
