### ISSUE TITLE
No Scrolling on User Popout Profiles

### ISSUE THREAD

**Issue by efidanza** [KillYoy/DiscordNight#50]
For people with many roles or long user descriptions you are unable to scroll down to see the entire mini profile/role list. It seems the scrollbar was entirely cutout from the code. However if you click the very bottom right corner it will instantly snap to the bottom of the role list and reveal the bottom of the profile and the message/notes

**Comment by efidanza** [comment]
After looking through the code for a while I found the code segment around line 10011 is what is effecting the scroll bar. by changing "overflow: hidden !important;" to "overflow: scroll !important;" brought back the scrolling function.
![image](https://github.com/KillYoy/DiscordNight/assets/80443041/7a8930c0-f808-44af-ba04-26e74659bf9f)

**Comment by KillYoy** [comment]
I have never seen this issue myself so never accounted for it and the scrollbar was hidden to begin with because otherwise even though its not currently visible it takes up space for the other elements. 
I have now made it so the scrollbar will still be hidden but now scrolling will work like it should.
